# __Notebook Imports__

In [0]:
import pandas as pd
import numpy as np

# __Constants__

In [0]:
TRAINING_DATA_FILE = '/content/train-data.txt'
TEST_DATA_FILE = '/content/test-data.txt'

TOKEN_SPAM_PROB_FILE = '/content/prob-spam.txt'
TOKEN_HAM_PROB_FILE = '/content/prob-nonspam.txt'
TOKEN_ALL_PROB_FILE = '/content/prob-all-tokens.txt'

VOCAB_SIZE = 2500

# __Read and Load Features from .txt Files imto NumPy Array__

In [0]:
sparse_train_data = np.loadtxt(TRAINING_DATA_FILE, delimiter=' ', dtype=int)

In [0]:
sparse_test_data = np.loadtxt(TEST_DATA_FILE, delimiter=' ', dtype=int)

In [8]:
sparse_train_data[:5] # test our train data

array([[  0,   0,   1,   1],
       [  0,  18,   1,   1],
       [  0,  94,   1,   1],
       [  0, 222,   1,   1],
       [  1,   3,   1,   1]])

In [9]:
sparse_train_data[:-5] # test our test data

array([[   0,    0,    1,    1],
       [   0,   18,    1,    1],
       [   0,   94,    1,    1],
       ...,
       [5795, 1826,    0,    1],
       [5795, 1875,    0,    1],
       [5795, 2007,    0,    1]])

In [10]:
print('Nr of rows in training file', sparse_train_data.shape[0])
print('Nr of rows in test file', sparse_test_data.shape[0])

Nr of rows in training file 262065
Nr of rows in test file 113822


In [11]:
print('Nr of email in training file', np.unique(sparse_train_data[:, 0]).size)

Nr of email in training file 4022


In [12]:
print('Nr of email in test file', np.unique(sparse_test_data[:, 0]).size)

Nr of email in test file 1717


### __How to create an Empty DataFrame__

In [14]:
column_names = ['DOC_ID'] + ['CATEGORY'] + list(range(0, VOCAB_SIZE))
column_names[:5]

['DOC_ID', 'CATEGORY', 0, 1, 2]

In [15]:
len(column_names)

2502

In [17]:
index_names = np.unique(sparse_train_data[:, 0])
index_names

array([   0,    1,    2, ..., 5791, 5794, 5795])

In [0]:
full_train_data = pd.DataFrame(index=index_names, columns=column_names)
full_train_data.fillna(value=0, inplace=True)

In [23]:
full_train_data.head()

DOC_ID  CATEGORY  0  1  2  3  4  ...  2493  2494  2495  2496  2497  2498  2499
0       0         0  0  0  0  0  0  ...     0     0     0     0     0     0     0
1       0         0  0  0  0  0  0  ...     0     0     0     0     0     0     0
2       0         0  0  0  0  0  0  ...     0     0     0     0     0     0     0
3       0         0  0  0  0  0  0  ...     0     0     0     0     0     0     0
4       0         0  0  0  0  0  0  ...     0     0     0     0     0     0     0

[5 rows x 2502 columns]

# __Create a Full Matrix from a Sparse Matrix__

In [0]:
def make_full_matrix(sparse_matrix, nr_words, doc_idx=0, word_idx=1, cat_idx=2, freq_idx=3):
  '''
  Form a full matrix from a sparse matrix. Return a pandas dataframe.
  Keyword arguments:
  sparse_matrix == numpy array
  nr_words == size of the vocabulary. Total number of tokens.
  doc_idx == position of the document id in the sparse matrix. Default: 1st column
  word_idx == position of the word id in the sparse matrix. Default: 2nd column
  cat_idx == position of the label (spam is 1, nonspam is 0). Default: 3rd column
  freq_idx == position of occurrence of word in sparse matrix. Default: 4th column
  '''

  column_names = ['DOC_ID'] + ['CATEGORY'] + list(range(0, VOCAB_SIZE))
  doc_id_names = np.unique(sparse_matrix[:, 0])
  full_matrix = pd.DataFrame(index=doc_id_names, columns=column_names)
  full_matrix.fillna(value=0, inplace=True)
  
  for i in range(sparse_matrix.shape[0]):
    doc_nr = sparse_matrix[i][doc_idx]
    word_id = sparse_matrix[i][word_idx]
    label = sparse_matrix[i][cat_idx]
    occurrence = sparse_matrix[i][freq_idx]

    full_matrix.at[doc_nr, 'DOC_ID'] = doc_nr
    full_matrix.at[doc_nr, 'CATEGORY'] = label
    full_matrix.at[doc_nr, word_id] = occurrence

  full_matrix.set_index('DOC_ID', inplace=True)
  return full_matrix

In [25]:
%%time
full_train_data = make_full_matrix(sparse_train_data, VOCAB_SIZE)

CPU times: user 9.03 s, sys: 87.3 ms, total: 9.11 s
Wall time: 9.13 s


In [27]:
full_train_data.tail()

CATEGORY  0  1  2  3  4  5  ...  2493  2494  2495  2496  2497  2498  2499
DOC_ID                              ...                                          
5789           0  1  3  1  0  0  0  ...     0     0     0     0     0     0     0
5790           0  1  0  1  0  0  1  ...     0     0     0     0     0     0     0
5791           0  2  0  1  0  0  0  ...     0     0     0     0     0     0     0
5794           0  1  0  0  0  0  1  ...     0     0     0     0     0     0     0
5795           0  1  1  2  0  2  1  ...     0     0     0     0     0     0     0

[5 rows x 2501 columns]

# __Training the Naive Bayes Model__
## __Calculating the Probability of Spam__

In [30]:
# Overall probability of spam
prob_spam = full_train_data.CATEGORY.sum() / full_train_data.CATEGORY.size
print('Probability of spam is', prob_spam)

Probability of spam is 0.3125310790651417


## __Total Number of Words/Tokens__

In [32]:
full_train_features = full_train_data.loc[:, full_train_data.columns !='CATEGORY']
full_train_features.head()

0     1     2     3     4     5     ...  2494  2495  2496  2497  2498  2499
DOC_ID                                      ...                                    
0          1     0     0     0     0     0  ...     0     0     0     0     0     0
1          0     0     0     1     0     0  ...     0     0     0     0     0     0
2          0     0     0     1     0     0  ...     0     0     0     0     0     0
3          0     0     1     1     0     0  ...     0     0     0     0     0     0
4          4     0     2     4     0     0  ...     0     0     0     0     0     0

[5 rows x 2500 columns]

In [33]:
email_lengths = full_train_features.sum(axis=1)
email_lengths.shape

(4022,)

In [35]:
email_lengths[:5]

DOC_ID
0      4
1    282
2     93
3     56
4    136
dtype: int64

In [37]:
total_wc = email_lengths.sum() # count the total number of tokens
total_wc

437358

## __Number of Tokens in Spam & Ham Emails__

In [38]:
spam_lengths = email_lengths[full_train_data.CATEGORY == 1]
spam_lengths.shape

(1257,)

In [39]:
spam_wc = spam_lengths.sum()
spam_wc

194472

In [40]:
ham_lengths = email_lengths[full_train_data.CATEGORY == 0]
ham_lengths.shape

(2765,)

In [42]:
email_lengths.shape[0] - spam_lengths.shape[0] - ham_lengths.shape[0] # check if subsets are correct

0

In [43]:
nonspam_wc = ham_lengths.sum()
nonspam_wc

242886

In [45]:
spam_wc + nonspam_wc - total_wc # quick check

0

In [51]:
print('Average nr of words in spam emails {:.0f}'.format(spam_wc / spam_lengths.shape[0]))
print('Average nr of words in ham emails {:.3f}'.format(nonspam_wc / ham_lengths.shape[0]))

Average nr of words in spam emails 155
Average nr of words in ham emails 87.843


## __Summing the Tokens Occuring in Spam__



In [52]:
full_train_features.shape

(4022, 2500)

In [54]:
train_spam_tokens = full_train_features.loc[full_train_data.CATEGORY == 1]
train_spam_tokens.tail()

0     1     2     3     4     5     ...  2494  2495  2496  2497  2498  2499
DOC_ID                                      ...                                    
1885       1     0     0     0     0     0  ...     0     0     0     0     0     0
1887       0     0     0     0     1     0  ...     0     0     0     0     0     0
1889       1     0     0     0     0     0  ...     0     0     0     0     0     0
1890       0     0     1     1     0     1  ...     0     0     0     0     0     0
1895       0     0     0     0     0     0  ...     0     0     0     0     0     0

[5 rows x 2500 columns]

In [55]:
train_spam_tokens.shape

(1257, 2500)

In [56]:
summed_spam_tokens = train_spam_tokens.sum(axis=0) + 1 # make calculation to avoid zero
summed_spam_tokens.shape

(2500,)

## __Summing the Tokens Occuring in Non-Spam Emails__


In [57]:
train_ham_tokens = full_train_features.loc[full_train_data.CATEGORY == 0]
train_ham_tokens.tail()

0     1     2     3     4     5     ...  2494  2495  2496  2497  2498  2499
DOC_ID                                      ...                                    
5789       1     3     1     0     0     0  ...     0     0     0     0     0     0
5790       1     0     1     0     0     1  ...     0     0     0     0     0     0
5791       2     0     1     0     0     0  ...     0     0     0     0     0     0
5794       1     0     0     0     0     1  ...     0     0     0     0     0     0
5795       1     1     2     0     2     1  ...     0     0     0     0     0     0

[5 rows x 2500 columns]

In [58]:
train_ham_tokens.shape

(2765, 2500)

In [59]:
summed_ham_tokens = train_ham_tokens.sum(axis=0) + 1 # make calculation to avoid zero
summed_ham_tokens.shape

(2500,)

## __P(Token | Spam) - Probability that a Token Occurs given the Email is Spam__

In [60]:
prob_tokens_spam = summed_spam_tokens / (spam_wc + VOCAB_SIZE)
prob_tokens_spam[:5]

0    0.011494
1    0.005031
2    0.006696
3    0.010565
4    0.007082
dtype: float64

In [61]:
prob_tokens_spam.sum()

1.0

## __P(Token | Ham) - Probability that a Token Occurs given the Email is Nonspam__

In [62]:
prob_tokens_nonspam = summed_ham_tokens / (nonspam_wc + VOCAB_SIZE)
prob_tokens_nonspam.sum()

1.0

# __P(Token) - Probability that Token Occurs__

In [0]:
prob_tokens_all = full_train_features.sum(axis=0) / total_wc

In [64]:
prob_tokens_all.sum()

1.0

# __Save the Trained Model__

In [0]:
np.savetxt(TOKEN_SPAM_PROB_FILE, prob_tokens_spam)
np.savetxt(TOKEN_HAM_PROB_FILE, prob_tokens_nonspam)
np.savetxt(TOKEN_ALL_PROB_FILE, prob_tokens_all)